train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: UDIS-D/training/input1/
      root_path_2: UDIS-D/training/input2/
      first_k: 10000

  wrapper:
    name: paired-images
    args: {}

  batch_size: 16


valid_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: UDIS-D/testing/input1/
      root_path_2: UDIS-D/testing/input2/

  wrapper:
    name: paired-images
    args: {}

  batch_size: 1

model:
  name: H-Cell
  args: {}


optimizer:
  name: adamw
  args:
    lr: 1.e-4

epoch_max: 100
epoch_save: 10

resume: save/_HCell/epoch-last.pth
